name: New Topic Request / 新增知识点建议
description: 建议增加某个新的学科、章节或特定知识点的笔记
labels: ["enhancement", "topic-request"]
body:
  - type: markdown
    attributes:
      value: |
        想看更多的内容？请告诉我们你感兴趣的领域。
  - type: input
    id: topic
    attributes:
      label: 建议的主题/章节
      placeholder: 例如：物理-电磁感应-涡流效应
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: 详细背景
      description: 为什么建议增加这个内容？是否有参考的教材或题目？
      placeholder: |
        在某次考试中遇到了这类题型，希望能总结一下相关的模型。
  - type: checkboxes
    id: priority
    attributes:
      label: 紧迫程度
      options:
        - label: 核心知识点 (推荐优先更新)
        - label: 拓展知识点
        - label: 趣味科学/冷知识
