name: CI/CD Pipeline

on:
  schedule:
    - cron: '0 0 * * 1'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ci-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pages: write
  packages: read
  id-token: write

jobs:
  build:
    name: Build for ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Github Pages
            cache: mkdocs-gh-nkr
            url: https://raineblog.dpdns.org/whk/
            branch: gh-pages
            disable_giscus: 'false'
          - name: Cloudflare Pages
            cache: mkdocs-cf-nkr
            url: https://raineblog-whk.pages.dev/
            branch: cloudflare-pages
            disable_giscus: 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Setup uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Install bun dependencies
        run: bun install

      - name: Install uv dependencies
        run: uv sync --locked --no-dev

      - name: Install pandoc
        uses: pandoc/actions/setup@v1

      - name: Cache
        uses: actions/cache@v5
        with:
          path: .cache
          key: ${{ runner.os }}-${{ matrix.cache }}-${{ github.run_id }}-${{ github.run_attempt }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.cache }}-

      - name: Build Static Site
        run: uv run --no-sync scripts/generate.py --build --site_url=${{ matrix.url }} --disable_giscus=${{ matrix.disable_giscus }}
        env:
          PYTHONUNBUFFERED: 1
          PYTHONUTF8: 1
          NO_MKDOCS_2_WARNING: 1

      - name: Build Bun Executable
        run: bun build --compile --minify --bytecode build.ts --outfile build-bin
      
      - name: Bun Post-processing
        run: ./build-bin --dir site

      - name: Push to Branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: ${{ matrix.branch }}
          publish_dir: site
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"

      - name: Upload Artifact
        if: matrix.branch == 'gh-pages'
        uses: actions/upload-pages-artifact@v4
        with:
          path: site

  deploy-artifact:
    name: Deploy to Github Pages
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Upload to GitHub Pages
        uses: actions/deploy-pages@v5
        id: deployment
